---
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: 
baseurl: 
logo: "/images/logo.png"
favicon: assets/images/favicon.png
locale: en_us
ganalytics: UA-48421544-1
social: "https://twitter.com/javasquare \nhttps://www.facebook.com/javasquare
  \nhttps://www.instagram.com/javasquare"
plugins:
    - jekyll-sitemap
    - jekyll-feed
    - jekyll-seo-tag
    - jekyll-archives
    - jekyll-algolia
  # Excluded items can be processed by explicitly listing the directories or
  #
  # exclude:
  #   - .sass-cache/
  #   - .jekyll-cache/
  #   - gemfiles/
  #   - Gemfile
  #   - Gemfile.lock
  #   - node_modules/
  #   - vendor/bundle/
  #   - vendor/cache/
  #   - vendor/gems/
  #   - vendor/ruby/